name: Test code

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Test pre-commit hooks
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit run -a
  test_code:
    runs-on: ubuntu-latest
    container: ghcr.io/gdsfactory/gdsfactory:main
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          make install
      - name: Test with pytest
        run: pytest tests/
